YMMaster/Controllers/DashBoardController.cs
using YMMaster.Models;
using MasterInterface.Implementation;
using MasterInterface.Interface;

using MasterInterface.Model;
using MasterRepository;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace YMMaster.Controllers
{
    
    public class DashBoardController : Controller
    {
        private IMenuService _MenuService;
        private ICommonService _Commonservice;

        private YMMasterEntities db;
        public DashBoardController()
        {
            _Commonservice = new CommonService();
            _MenuService = new MenuService();
        }

        public ActionResult Index()
        {
            var RoleId = ((ClaimsIdentity)User.Identity).FindFirst("RoleId").Value;
            List<MenuModel> Record = _MenuService.GetAllActiveMenus(Convert.ToInt32(RoleId));
            return View(Record);

        }



        public ActionResult Student()
        {
            var RoleId = ((ClaimsIdentity)User.Identity).FindFirst("RoleId").Value;
            List<MenuModel> Record = _MenuService.GetAllActiveMenus(Convert.ToInt32(RoleId));
            return View(Record);

        }
        public ActionResult Admin()
        {
            var RoleId = ((ClaimsIdentity)User.Identity).FindFirst("RoleId").Value;
            List<MenuModel> Record = _MenuService.GetAllActiveMenus(Convert.ToInt32(RoleId));
            return View(Record);

        }
        public ActionResult College()
        {
            var RoleId = ((ClaimsIdentity)User.Identity).FindFirst("RoleId").Value;
            List<MenuModel> Record = _MenuService.GetAllActiveMenus(Convert.ToInt32(RoleId));
            return View(Record);

        }
        public ActionResult Menu()
        {
            var RoleId = ((ClaimsIdentity)User.Identity).FindFirst("RoleId").Value;
            List<MenuModel> Record = _MenuService.GetAllActiveMenus(Convert.ToInt32(RoleId));
            return View(Record);

        }


        public ActionResult Course()
        {
            var RoleId = ((ClaimsIdentity)User.Identity).FindFirst("RoleId").Value;
            List<MenuModel> Record = _MenuService.GetAllActiveMenus(Convert.ToInt32(RoleId));
            return View(Record);

        }

        public ActionResult UnAuthorized()
        {
            return View();
        }
       
  }
}

YMMaster/Controllers/Setup/MenuController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.Setup
{
    
    public class MenuController : Controller
    {
        private ISetupService _SetupService;
    

           public MenuController()
        {
            _SetupService = new SetupService();
            
        }
        public ActionResult Index()
        {
            List<MenuModel> Record = _SetupService.GetAllMenus();
            return View("../Setup/Menu/Index", Record);
        }
        
        public ActionResult Create()
        {
            MenuModel Record = new MenuModel();
            Record.ParentMenu = _SetupService.GetParentMenus();
            return View("../Setup/Menu/Create", Record);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MenuModel Record)
        {
           
            Record.ParentMenu = _SetupService.GetParentMenus();
            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.AddMenu(Record);
                    TempData["Success"] = "Menu added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;

            }
            return View("../Menu/MenuSetup/Create", Record);
        }

       
        [HttpGet]
        public ActionResult Update(int Id)
        {
            MenuModel Record = new MenuModel();
            Record = _SetupService.GetOneMenu(Id);
            Record.ParentMenu = _SetupService.GetParentMenus();
            return View("../Setup/Menu/Update", Record);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(MenuModel Record)
        {
            Record.ParentMenu = _SetupService.GetParentMenus();
            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.UpdateMenu(Record);
                    TempData["Success"] = "Menu updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
            }

            return View("../Setup/Menu//Update", Record);
        }

      


    }
}

YMMaster/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YMMaster.Controllers
{
    public class StudentController : Controller
    {
        
        // GET: Student
        public ActionResult Index()
        {
            return View();
        }
    }
}

YMMaster/Views/DashBoard/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin</h2>

@section PageHeader{
    <div class="small-header">
        <div class="hpanel">

            @foreach (var item in Model)
            {

                <div class="col-sm-2" style="min-height: 180px;">
                    <div class="box box-top-border">
                        <a href="~/@item.Controller/@item.MenuLink">
                            <div class="hero-widget well-menu well-sm" style="min-height: 150px">
                                <div class="icon" style="text-align:center;">
                                    <i class="@item.CssClass" style="font-size:45px; text-align:center;" aria-hidden="true"></i>
                                </div>
                                <div class="text" style="text-align:center; padding-top:30%;">
                                    <label class="text-muted"
                                           style="font-size: 14px">@item.Name</label>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>

            }



        </div>
    </div>
}

YMMaster/Views/DashBoard/College.cshtml
@{
    ViewBag.Title = "College";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>College</h2>


@section PageHeader{
    <div class="small-header">
        <div class="hpanel">



            <div class="col-sm-2" style="min-height: 180px;">
                <div class="box box-top-border">
                    <a href="">
                        <div class="hero-widget well-menu well-sm" style="min-height: 150px">
                            <div class="icon" style="text-align:center;">
                                <i class="" style="font-size:45px; text-align:center;" aria-hidden="true"></i>
                            </div>
                            <div class="text" style="text-align:center; padding-top:30%;">
                                <label class="text-muted"
                                       style="font-size: 14px">CollegeRole</label>
                            </div>
                        </div>
                    </a>
                </div>
            </div>




        </div>
    </div>
}

YMMaster/Views/DashBoard/Course.cshtml
@model IEnumerable<MasterInterface.Model.MenuModel>


@{
    ViewBag.Title = "Course";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@section PageHeader{
    <div class="small-header">
        <div class="hpanel">
                              
                        @foreach (var item in Model)
                        {

                            <div class="col-sm-2" style="min-height: 180px;">
                                <div class="box box-top-border">
                                    <a href="~/@item.Controller/@item.MenuLink">
                                        <div class="hero-widget well-menu well-sm" style="min-height: 150px">
                                            <div class="icon" style="text-align:center;">
                                                <i class="@item.CssClass" style="font-size:45px; text-align:center;" aria-hidden="true"></i>
                                            </div>
                                            <div class="text" style="text-align:center; padding-top:30%;">
                                                <label class="text-muted"
                                                       style="font-size: 14px">@item.Name</label>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>

                        }
               

                
        </div>
    </div>
}

YMMaster/Views/DashBoard/Index.cshtml
@model IEnumerable<MasterInterface.Model.MenuModel>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@section PageHeader{
    <div class="small-header">
        <div class="hpanel">
                              
                        @foreach (var item in Model)
                        {

                            <div class="col-sm-2" style="min-height: 180px;">
                                <div class="box box-top-border">
                                    <a href="~/@item.Controller/@item.MenuLink">
                                        <div class="hero-widget well-menu well-sm" style="min-height: 150px">
                                            <div class="icon" style="text-align:center;">
                                                <i class="@item.CssClass" style="font-size:45px; text-align:center;" aria-hidden="true"></i>
                                            </div>
                                            <div class="text" style="text-align:center; padding-top:30%;">
                                                <label class="text-muted"
                                                       style="font-size: 14px">@item.Name</label>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>

                        }
               

                
        </div>
    </div>
}

YMMaster/Views/DashBoard/Menu.cshtml
@model IEnumerable<MasterInterface.Model.MenuModel>


@{
    ViewBag.Title = "Exam Center";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@section PageHeader{
    <div class="small-header">
        <div class="hpanel">
                              
                        @foreach (var item in Model)
                        {

                            <div class="col-sm-2" style="min-height: 180px;">
                                <div class="box box-top-border">
                                    <a href="~/@item.Controller/@item.MenuLink">
                                        <div class="hero-widget well-menu well-sm" style="min-height: 150px">
                                            <div class="icon" style="text-align:center;">
                                                <i class="@item.CssClass" style="font-size:45px; text-align:center;" aria-hidden="true"></i>
                                            </div>
                                            <div class="text" style="text-align:center; padding-top:30%;">
                                                <label class="text-muted"
                                                       style="font-size: 14px">@item.Name</label>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>

                        }
               

                
        </div>
    </div>
}

YMMaster/Views/DashBoard/Student.cshtml
@model IEnumerable<MasterInterface.Model.MenuModel>


@{
    ViewBag.Title = "Student";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>student</h2>


@section PageHeader{
    <div class="small-header">
        <div class="hpanel">
             <div class="col-sm-2" style="min-height: 180px;">
                                <div class="box box-top-border">
                                    <a href="">
                                        <div class="hero-widget well-menu well-sm" style="min-height: 150px">
                                            <div class="icon" style="text-align:center;">
                                                <i class="" style="font-size:45px; text-align:center;" aria-hidden="true"></i>
                                            </div>
                                            <div class="text" style="text-align:center; padding-top:30%;">
                                                <label class="text-muted"
                                                       style="font-size: 14px">StudentRole</label>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>

               

                
        </div>
    </div>
}

YMMaster/Views/DashBoard/UnAuthorized.cshtml
@{
    ViewBag.Title = "UnAuthorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UnAuthorized</h2>

<h3>Sorry !! You arenot authorized to perform this action.<br/>
    Please Contact the System Administrator.
    <br/>
    Thank You!!!</h3>

YMMaster/Views/DashBoard/VoucherUpload.cshtml
@{
    ViewBag.Title = "VoucherUpload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Upload Voucher</h4>
<hr />
@using (Html.BeginForm("VoucherUpload", "DashBoard", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return myFunction()" }))
{


    <div class="form-horizontal">



        <div class="form-group">

            <div class="control-label col-md-2">Excel:</div>
            <div class="col-md-10">
                <input type="file" id="file" name="file" class="" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" id="btnSubmit" class="btn btn-primary" />

            </div>
        </div>
    </div>
}