YMMaster/Controllers/Setup/AssignMenuController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using MasterRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;


namespace YMMaster.Controllers.Setup
{
   [HasCompanyId]
    public class AssignMenuController : Controller
    {
        private YMMasterEntities db;
        private ISetupService _SetupService;

        public AssignMenuController()
        {
            db = new YMMasterEntities();
        _SetupService = new SetupService();
    }
        //Get Role List
        public ActionResult Index()

        {
            List<RoleModel> Record=_SetupService.GetAllRoles();
            return View("../Setup/AssignMenu/Index",Record);
        }

        //Get Menu List 
        [HttpGet]
        public ActionResult RoleMenuAccessSetup(int id)
        {
            AssignMenuModel Record = _SetupService.GetRoleAccess(id);
            var data = db.Roles.Find(id);
            ViewBag.RoleName = data.Name;
            return View("../Setup/AssignMenu/RoleMenuAccessSetup", Record);
        }

        [HttpPost]
        public ActionResult RoleMenuAccessSetup(AssignMenuModel Record)
        {
            try
            {
                _SetupService.AddRoleAccess(Record);
                TempData["Success"] = "Role Assigned successfully";
            }
            catch (Exception Exception)
            {
                 TempData["Danger"] = Exception.Message;
                 return RedirectToAction("Index");
            }
            return View("../Setup/AssignMenu/RoleMenuAccessSetup",Record);
        }
    }
}

YMMaster/Controllers/Setup/CollegeUserController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.Setup
{
    [Authorize(Roles = "SuperAdmin,IOE")]
    public class CollegeUserController : Controller
    {
        private IUserService _UserService = null;
        private ICourseService _CourseService = null;
        public CollegeUserController()
        {
            _UserService = new UserService();
            _CourseService = new CourseService();
        }

        // GET: CollegeUser
        public ActionResult Index()
        {
            List<CourseInstituteBodyModel> Record = _CourseService.GetAllCourseInstituteBody();
            return View("../Setup/CollegeUser/Index", Record);
        }

        public ActionResult Create(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetCollegeUserModelCreateFor(Id);
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            
            return View("../Setup/CollegeUser/Create", Record);
        }

        [HttpPost]
        public ActionResult Create(UserModel Record)
        {
            
            Record.CourseInstituteBodySelectListItem = _CourseService.GetCourseInstituteBodySelectList();
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.AddCollegeUser(Record);
                    TempData["Success"] = "Institute Body added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");
            }

            return View("../Setup/CollegeUser/Create", Record);
        }


        public ActionResult Update(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetCollegeUserModelUpdateFor(Id);
            return View("../Setup/CollegeUser/Update", Record);
        }

        [HttpPost]
        public ActionResult Update(UserModel Record)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.UpdateCollegeUser(Record);
                    TempData["Success"] = "Institute Body updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");
            }

            return View("../Setup/CollegeUser/Update", Record);
        }

        public ActionResult Reset(int Id)
        {
            _UserService.ResetCollegeUser(Id);
            TempData["Success"] = "Password reset successfully";
            return RedirectToAction("Index");
        }
    }
}

YMMaster/Controllers/Setup/ExamFeeStructureController.cs
using IOEInterface.Implementation;
using IOEInterface.Interface;
using IOEInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.ExamFeeStructure
{
    [Authorize(Roles = "SuperAdmin")]
    public class ExamFeeStructureController : Controller
    {
        private IExamService _Examservice;
        public ExamFeeStructureController()
        {
            _Examservice = new ExamService();
        }
        public ActionResult Index()
        {
            List<ExamFeeStructureModel> Record = _Examservice.GetAllExamFeeStructures();
            return View("../Setup/ExamFeeStructure/Index", Record);
        }
        public ActionResult Create()
        {
            ExamFeeStructureModel Record = new ExamFeeStructureModel();
            return View("../Setup/ExamFeeStructure/Create", Record);
        }

        [HttpPost]
        public ActionResult Create(ExamFeeStructureModel Record)
        {
              try
            {
                if (ModelState.IsValid)
                {
                    _Examservice.AddExamFeeStructure(Record);
                    TempData["Success"] = "ExamFeeStructure added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");

            }
            return View("../Setup/ExamFeeStructure/Create", Record);
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            ExamFeeStructureModel Record = new ExamFeeStructureModel();
            Record = _Examservice.GetOneExamFeeStructure(Id);
            return View("../Setup/ExamFeeStructure/Update", Record);

        }

        [HttpPost]
        public ActionResult Update(ExamFeeStructureModel Record)
        {
              try
            {
                if (ModelState.IsValid)
                {
                    _Examservice.UpdateExamFeeStructure(Record);
                    TempData["Success"] = "ExamFeeStructure updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");
            }

            return View("../Setup/ExamFeeStructure/Update", Record);
        }

       
    }
}

YMMaster/Controllers/Setup/MenuController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.Setup
{
    
    public class MenuController : Controller
    {
        private ISetupService _SetupService;
    

           public MenuController()
        {
            _SetupService = new SetupService();
            
        }
        public ActionResult Index()
        {
            List<MenuModel> Record = _SetupService.GetAllMenus();
            return View("../Setup/Menu/Index", Record);
        }
        
        public ActionResult Create()
        {
            MenuModel Record = new MenuModel();
            Record.ParentMenu = _SetupService.GetParentMenus();
            return View("../Setup/Menu/Create", Record);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MenuModel Record)
        {
           
            Record.ParentMenu = _SetupService.GetParentMenus();
            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.AddMenu(Record);
                    TempData["Success"] = "Menu added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;

            }
            return View("../Menu/MenuSetup/Create", Record);
        }

       
        [HttpGet]
        public ActionResult Update(int Id)
        {
            MenuModel Record = new MenuModel();
            Record = _SetupService.GetOneMenu(Id);
            Record.ParentMenu = _SetupService.GetParentMenus();
            return View("../Setup/Menu/Update", Record);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(MenuModel Record)
        {
            Record.ParentMenu = _SetupService.GetParentMenus();
            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.UpdateMenu(Record);
                    TempData["Success"] = "Menu updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
            }

            return View("../Setup/Menu//Update", Record);
        }

      


    }
}

YMMaster/Controllers/Setup/RoleController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YMMaster.Controllers;

namespace IOEExamRegistration.Controllers.Setup
{  [HasCompanyId]
    public class RoleController : Controller
    {
        private ISetupService _SetupService;

        public RoleController()
        {
            _SetupService = new SetupService();
        }
        public ActionResult Index()
        {
            List<RoleModel> Record = _SetupService.GetAllRoles();
            return View("../Setup/Role/Index", Record);
        }

        public ActionResult Create()
        {
            RoleModel Record = new RoleModel();
            return View("../Setup/Role/Create", Record);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoleModel Record)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.AddRole(Record);
                    TempData["Success"] = "Role added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;

            }
            return View("../Setup/Role/Create", Record);
        }


        [HttpGet]
        public ActionResult Update(int Id)
        {
            RoleModel Record = new RoleModel();
            Record = _SetupService.GetOneRole(Id);
            return View("../Setup/Role/Update", Record);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(RoleModel Record)
        {
           try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.UpdateRole(Record);
                    TempData["Success"] = "Role updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
            }

            return View("../Setup/Role//Update", Record);
        }


    }
}

YMMaster/Controllers/Setup/StudentUserController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.Setup
{
    [Authorize(Roles = "SuperAdmin,IOE")]
    public class StudentUserController : Controller
    {
        IStudentService _StudentService;
        IUserService _UserService;


        public StudentUserController()
        {
            _StudentService = new StudentService();
            _UserService = new UserService();
        }
        // GET: StudentUser
        public ActionResult Index()
        {
            StudentModel Record = new StudentModel();
            Record.CourseInstituteBodySelectList = _StudentService.GetInsituteBodyList();
            return View("../Setup/StudentUser/Index", Record);
        }

        [HttpGet]
        public ActionResult Get()
        {
            List<StudentModel> Record = new List<StudentModel>();
            return View("../Setup/StudentUser/Get", Record);
        }

        [HttpPost]
        public ActionResult Get(int InstituteBodyId = 0)
        {
            List<StudentModel> Record = _StudentService.GetAllStudentByInstituteBodyId(InstituteBodyId);
            return View("../Setup/StudentUser/Get", Record);
               }

       


        public ActionResult Create(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetStudentUserModelCreateFor(Id);
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            return View("../Setup/StudentUser/Create", Record);
        }

        [HttpPost]
        public ActionResult Create(UserModel Record)
        {
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.AddStudentUser(Record);
                    TempData["Success"] = "Student User added successfully";
                    return RedirectToAction("Get");
                }
                else
                {
                    TempData["Danger"] = "Form error";

                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Get");
            }

            return View("../Setup/StudentUser/Create", Record);
        }

        public ActionResult Update(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetStudentUserModelUpdateFor(Id);
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            return View("../Setup/StudentUser/Update", Record);
        }


        [HttpPost]
        public ActionResult Update(UserModel Record)
        {
            Record.StudentSelectListItem = _UserService.GetStudentSelectList();
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.UpdateStudentUser(Record);
                    TempData["Success"] = "Student User updated successfully";
                    return RedirectToAction("Get");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Get");
            }

            return View("../Setup/StudentUser/Update", Record);
        }

        public ActionResult Reset(int Id)
        {
            _UserService.ResetStudentUser(Id);
            TempData["Success"] = "Password reset successfully";
            return RedirectToAction("Get");
        }

    }
}

YMMaster/Views/Setup/Menu/Create.cshtml
@model MasterInterface.Model.MenuModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section PageHeader{
    <div class="small-header">
        <div class="hpanel">
            <div class="panel-body">
                <div id="hbreadcrumb" class="pull-right">
                    <ol class="hbreadcrumb breadcrumb">
                        <li class="active"><span><a href='@Url.Action("Index","Menu")'>Back to list</a></span></li>
                    </ol>
                </div>
                <h2 class="font-light m-b-xs">
                    Menu
                </h2>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ParentId,Model.ParentMenu, "Please Select" , new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CssClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CssClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CssClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Controller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Controller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Controller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDefault, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDefault)
                    @Html.ValidationMessageFor(model => model.IsDefault, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

YMMaster/Views/Setup/Menu/Index.cshtml
@model IEnumerable<MasterInterface.Model.MenuModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section PageHeader{
    <div class="small-header">
        <div class="hpanel">
            <div class="panel-body">
                <div id="hbreadcrumb" class="pull-right">
                    <ol class="hbreadcrumb breadcrumb">
                        <li class="active"><span>@Html.ActionLink("Create New", "Create")</span></li>
                    </ol>
                </div>
                <h2 class="font-light m-b-xs">
                    Menu
                </h2>
            </div>
        </div>
    </div>
}



<div class="panel panel-default">
    <div class="panel-body">
        <table class="table table-bordered">

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ParentId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CssClass)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MenuLink)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Order)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Controller)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsDefault)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => item.Id)
                        @Html.DisplayFor(modelItem => item.ParentId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CssClass)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MenuLink)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Order)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Controller)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsDefault)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Update", new { id = item.Id })

                    </td>
                </tr>
            }

        </table>
        </div>
</div>

YMMaster/Views/Setup/Menu/Update.cshtml
@model MasterInterface.Model.MenuModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section PageHeader{
    <div class="small-header">
        <div class="hpanel">
            <div class="panel-body">
                <div id="hbreadcrumb" class="pull-right">
                    <ol class="hbreadcrumb breadcrumb">
                        <li class="active"><span><a href='@Url.Action("Index","Menu")'>Back to list</a></span></li>
                    </ol>
                </div>
                <h2 class="font-light m-b-xs">
                    Menu
                </h2>
            </div>
        </div>
    </div>
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ParentId, Model.ParentMenu, "Please Select", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CssClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CssClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CssClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Controller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Controller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Controller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDefault, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDefault)
                    @Html.ValidationMessageFor(model => model.IsDefault, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}