YMMaster/Controllers/Setup/AssignMenuController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using MasterRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;


namespace YMMaster.Controllers.Setup
{
   [HasCompanyId]
    public class AssignMenuController : Controller
    {
        private YMMasterEntities db;
        private ISetupService _SetupService;

        public AssignMenuController()
        {
            db = new YMMasterEntities();
        _SetupService = new SetupService();
    }
        //Get Role List
        public ActionResult Index()

        {
            List<RoleModel> Record=_SetupService.GetAllRoles();
            return View("../Setup/AssignMenu/Index",Record);
        }

        //Get Menu List 
        [HttpGet]
        public ActionResult RoleMenuAccessSetup(int id)
        {
            AssignMenuModel Record = _SetupService.GetRoleAccess(id);
            var data = db.Roles.Find(id);
            ViewBag.RoleName = data.Name;
            return View("../Setup/AssignMenu/RoleMenuAccessSetup", Record);
        }

        [HttpPost]
        public ActionResult RoleMenuAccessSetup(AssignMenuModel Record)
        {
            try
            {
                _SetupService.AddRoleAccess(Record);
                TempData["Success"] = "Role Assigned successfully";
            }
            catch (Exception Exception)
            {
                 TempData["Danger"] = Exception.Message;
                 return RedirectToAction("Index");
            }
            return View("../Setup/AssignMenu/RoleMenuAccessSetup",Record);
        }
    }
}

YMMaster/Controllers/Setup/CollegeUserController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.Setup
{
    [Authorize(Roles = "SuperAdmin,IOE")]
    public class CollegeUserController : Controller
    {
        private IUserService _UserService = null;
        private ICourseService _CourseService = null;
        public CollegeUserController()
        {
            _UserService = new UserService();
            _CourseService = new CourseService();
        }

        // GET: CollegeUser
        public ActionResult Index()
        {
            List<CourseInstituteBodyModel> Record = _CourseService.GetAllCourseInstituteBody();
            return View("../Setup/CollegeUser/Index", Record);
        }

        public ActionResult Create(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetCollegeUserModelCreateFor(Id);
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            
            return View("../Setup/CollegeUser/Create", Record);
        }

        [HttpPost]
        public ActionResult Create(UserModel Record)
        {
            
            Record.CourseInstituteBodySelectListItem = _CourseService.GetCourseInstituteBodySelectList();
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.AddCollegeUser(Record);
                    TempData["Success"] = "Institute Body added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");
            }

            return View("../Setup/CollegeUser/Create", Record);
        }


        public ActionResult Update(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetCollegeUserModelUpdateFor(Id);
            return View("../Setup/CollegeUser/Update", Record);
        }

        [HttpPost]
        public ActionResult Update(UserModel Record)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.UpdateCollegeUser(Record);
                    TempData["Success"] = "Institute Body updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");
            }

            return View("../Setup/CollegeUser/Update", Record);
        }

        public ActionResult Reset(int Id)
        {
            _UserService.ResetCollegeUser(Id);
            TempData["Success"] = "Password reset successfully";
            return RedirectToAction("Index");
        }
    }
}

YMMaster/Controllers/Setup/ExamFeeStructureController.cs
using IOEInterface.Implementation;
using IOEInterface.Interface;
using IOEInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.ExamFeeStructure
{
    [Authorize(Roles = "SuperAdmin")]
    public class ExamFeeStructureController : Controller
    {
        private IExamService _Examservice;
        public ExamFeeStructureController()
        {
            _Examservice = new ExamService();
        }
        public ActionResult Index()
        {
            List<ExamFeeStructureModel> Record = _Examservice.GetAllExamFeeStructures();
            return View("../Setup/ExamFeeStructure/Index", Record);
        }
        public ActionResult Create()
        {
            ExamFeeStructureModel Record = new ExamFeeStructureModel();
            return View("../Setup/ExamFeeStructure/Create", Record);
        }

        [HttpPost]
        public ActionResult Create(ExamFeeStructureModel Record)
        {
              try
            {
                if (ModelState.IsValid)
                {
                    _Examservice.AddExamFeeStructure(Record);
                    TempData["Success"] = "ExamFeeStructure added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");

            }
            return View("../Setup/ExamFeeStructure/Create", Record);
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            ExamFeeStructureModel Record = new ExamFeeStructureModel();
            Record = _Examservice.GetOneExamFeeStructure(Id);
            return View("../Setup/ExamFeeStructure/Update", Record);

        }

        [HttpPost]
        public ActionResult Update(ExamFeeStructureModel Record)
        {
              try
            {
                if (ModelState.IsValid)
                {
                    _Examservice.UpdateExamFeeStructure(Record);
                    TempData["Success"] = "ExamFeeStructure updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Index");
            }

            return View("../Setup/ExamFeeStructure/Update", Record);
        }

       
    }
}

YMMaster/Controllers/Setup/MenuController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.Setup
{
    
    public class MenuController : Controller
    {
        private ISetupService _SetupService;
    

           public MenuController()
        {
            _SetupService = new SetupService();
            
        }
        public ActionResult Index()
        {
            List<MenuModel> Record = _SetupService.GetAllMenus();
            return View("../Setup/Menu/Index", Record);
        }
        
        public ActionResult Create()
        {
            MenuModel Record = new MenuModel();
            Record.ParentMenu = _SetupService.GetParentMenus();
            return View("../Setup/Menu/Create", Record);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MenuModel Record)
        {
           
            Record.ParentMenu = _SetupService.GetParentMenus();
            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.AddMenu(Record);
                    TempData["Success"] = "Menu added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;

            }
            return View("../Menu/MenuSetup/Create", Record);
        }

       
        [HttpGet]
        public ActionResult Update(int Id)
        {
            MenuModel Record = new MenuModel();
            Record = _SetupService.GetOneMenu(Id);
            Record.ParentMenu = _SetupService.GetParentMenus();
            return View("../Setup/Menu/Update", Record);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(MenuModel Record)
        {
            Record.ParentMenu = _SetupService.GetParentMenus();
            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.UpdateMenu(Record);
                    TempData["Success"] = "Menu updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
            }

            return View("../Setup/Menu//Update", Record);
        }

      


    }
}

YMMaster/Controllers/Setup/RoleController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YMMaster.Controllers;

namespace IOEExamRegistration.Controllers.Setup
{  [HasCompanyId]
    public class RoleController : Controller
    {
        private ISetupService _SetupService;

        public RoleController()
        {
            _SetupService = new SetupService();
        }
        public ActionResult Index()
        {
            List<RoleModel> Record = _SetupService.GetAllRoles();
            return View("../Setup/Role/Index", Record);
        }

        public ActionResult Create()
        {
            RoleModel Record = new RoleModel();
            return View("../Setup/Role/Create", Record);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoleModel Record)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.AddRole(Record);
                    TempData["Success"] = "Role added successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;

            }
            return View("../Setup/Role/Create", Record);
        }


        [HttpGet]
        public ActionResult Update(int Id)
        {
            RoleModel Record = new RoleModel();
            Record = _SetupService.GetOneRole(Id);
            return View("../Setup/Role/Update", Record);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(RoleModel Record)
        {
           try
            {
                if (ModelState.IsValid)
                {
                    _SetupService.UpdateRole(Record);
                    TempData["Success"] = "Role updated successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
            }

            return View("../Setup/Role//Update", Record);
        }


    }
}

YMMaster/Controllers/Setup/StudentUserController.cs
using MasterInterface.Implementation;
using MasterInterface.Interface;
using MasterInterface.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace IOEExamRegistration.Controllers.Setup
{
    [Authorize(Roles = "SuperAdmin,IOE")]
    public class StudentUserController : Controller
    {
        IStudentService _StudentService;
        IUserService _UserService;


        public StudentUserController()
        {
            _StudentService = new StudentService();
            _UserService = new UserService();
        }
        // GET: StudentUser
        public ActionResult Index()
        {
            StudentModel Record = new StudentModel();
            Record.CourseInstituteBodySelectList = _StudentService.GetInsituteBodyList();
            return View("../Setup/StudentUser/Index", Record);
        }

        [HttpGet]
        public ActionResult Get()
        {
            List<StudentModel> Record = new List<StudentModel>();
            return View("../Setup/StudentUser/Get", Record);
        }

        [HttpPost]
        public ActionResult Get(int InstituteBodyId = 0)
        {
            List<StudentModel> Record = _StudentService.GetAllStudentByInstituteBodyId(InstituteBodyId);
            return View("../Setup/StudentUser/Get", Record);
               }

       


        public ActionResult Create(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetStudentUserModelCreateFor(Id);
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            return View("../Setup/StudentUser/Create", Record);
        }

        [HttpPost]
        public ActionResult Create(UserModel Record)
        {
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.AddStudentUser(Record);
                    TempData["Success"] = "Student User added successfully";
                    return RedirectToAction("Get");
                }
                else
                {
                    TempData["Danger"] = "Form error";

                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Get");
            }

            return View("../Setup/StudentUser/Create", Record);
        }

        public ActionResult Update(int Id)
        {
            UserModel Record = new UserModel();
            Record = _UserService.GetStudentUserModelUpdateFor(Id);
            var LoginId = ((ClaimsIdentity)User.Identity).FindFirst("LoginId").Value;
            Record.CreatedBy = Convert.ToInt32(LoginId);
            Record.CreatedOn = DateTime.Now;
            return View("../Setup/StudentUser/Update", Record);
        }


        [HttpPost]
        public ActionResult Update(UserModel Record)
        {
            Record.StudentSelectListItem = _UserService.GetStudentSelectList();
            try
            {
                if (ModelState.IsValid)
                {
                    _UserService.UpdateStudentUser(Record);
                    TempData["Success"] = "Student User updated successfully";
                    return RedirectToAction("Get");
                }
                else
                {
                    TempData["Danger"] = "Form error";
                }
            }
            catch (Exception Exception)
            {
                TempData["Danger"] = Exception.Message;
                return RedirectToAction("Get");
            }

            return View("../Setup/StudentUser/Update", Record);
        }

        public ActionResult Reset(int Id)
        {
            _UserService.ResetStudentUser(Id);
            TempData["Success"] = "Password reset successfully";
            return RedirectToAction("Get");
        }

    }
}

YMMaster/Views/Setup/AssignMenu/Index.cshtml
@model IEnumerable<MasterInterface.Model.RoleModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Detail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccessAll)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.HiddenFor(modelItem => item.Id)
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Detail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccessAll)
            </td>
            <td>
                @Html.ActionLink("Edit", "RoleMenuAccessSetup", new { id = item.Id })
                @Html.ActionLink("Assign Menu", "RoleMenuAccessSetup", "AssignMenu", new { id = item.Id })
            </td>
        </tr>
    }

</table>

YMMaster/Views/Setup/AssignMenu/RoleMenuAccessSetup.cshtml
@model MasterInterface.Model.AssignMenuModel

@{
    ViewBag.Title = "RoleMenuAccessSetup";
    Layout = "~/Views/Shared/_Layout.cshtml";
  
}

<h3>RoleMenuAccessSetup   [  @ViewBag.RoleName  ]</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.RoleId, new { htmlAttributes = new { @class = "form-control" } })
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <table class="table">
            <tr>
                <th><input type="checkbox" id="SelectAll"></th>
                <th>Menu</th>
                <th>Create</th>
                <th>Read</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>


            @for (int i = 0; i <= Model.Menu.Count - 1; i++)
            {
                <tr>
                    <td>
                        @Html.CheckBoxFor(model => model.Menu[i].IsSelected, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Menu[i].IsSelected, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.HiddenFor(model => model.Menu[i].Id)
                        @Html.DisplayFor(model => model.Menu[i].Name)
                    </td>
                    <td>
                        @Html.CheckBoxFor(model => model.Menu[i].Create, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Menu[i].Create, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.CheckBoxFor(model => model.Menu[i].Read, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Menu[i].Read, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.CheckBoxFor(model => model.Menu[i].Update, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Menu[i].Update, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.CheckBoxFor(model => model.Menu[i].Delete, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Menu[i].Delete, "", new { @class = "text-danger" })
                    </td>
                </tr>
            }
        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#SelectAll").click(function () {

            if ($("#SelectAll").prop('checked')) {
                $("input[type=checkbox]").each(function () {
                    $(this).prop('checked', true)
                });
            }
            else {
                $("input[type=checkbox]").each(function () {
                    $(this).prop('checked', false)
                });
            }
        });



    </script>
}